name: Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        os: [linux, win]
        include:
          - os: linux
            runner: ubuntu-22.04
            executable: yer
          - os: win
            runner: windows-2022
            executable: yer.exe
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: yer-build-${{ matrix.os }}-${{ hashFiles('**/Cargo.toml') }}
    - name: Install Linux dependencies
      if: ${{ matrix.os == 'linux' }}
      run: |
        sudo apt-get update
        sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release --no-default-features --verbose
    - name: Rename executable
      id: rename-executable
      shell: bash
      run: |
        CRATE_VERSION=$(cargo pkgid | cut -d "#" -f2)
        GIT_REVISION=$(git rev-parse --short=7 HEAD)
        BRANCH="${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}"
        NAME="yer-$CRATE_VERSION-dev-$BRANCH-$GIT_REVISION-${{ matrix.os }}"
        if [ ${{ matrix.os }} = "linux" ]; then
            FILENAME=$NAME
        fi;
        if [ ${{ matrix.os }} = "win" ]; then
            FILENAME="$NAME.exe"
        fi;
        echo "name=$NAME" >> "$GITHUB_OUTPUT"
        echo "filename=$FILENAME" >> "$GITHUB_OUTPUT"
        mkdir target/release/$NAME
        cp target/release/${{ matrix.executable }} target/release/$NAME/$FILENAME
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.rename-executable.outputs.name }}
        path: target/release/${{ steps.rename-executable.outputs.name }}
