name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
        include:
          - os: ubuntu-22.04
            executable: yer
          - os: windows-2022
            executable: yer.exe
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: yer-build-${{ matrix.os }}-${{ hashFiles('**/Cargo.toml') }}
    - name: Install Linux dependencies
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: |
        sudo apt-get update
        sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0      
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release --no-default-features --verbose
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: Executable for ${{ matrix.os }}
        path: target/release/${{ matrix.executable }}
